### ISSUE TITLE
Semantic Linter and Release GitHub action discrepancy 

### ISSUE THREAD

**Issue by SHession** [guardian/prosemirror-elements#222]
## Problem

At the moment their is an inconsistency between the semantic [release linter](https://github.com/guardian/prosemirror-elements/blob/main/.github/workflows/semantic-pr.yml) and the [release action](https://github.com/guardian/prosemirror-elements/blob/bf077764d9af4f78dac6d2e4840b3e132fd4d735/.github/workflows/build-and-release.yml#L71). The use different conventions to determine how the version should be bumped. The linter uses [Conventional Commits spec](https://www.conventionalcommits.org/) and the release uses [angular](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular). Regardless of which convention we would prefer we should ensure it's consistent so release never [fail](https://github.com/guardian/prosemirror-elements/runs/5534757285?check_suite_focus=true#step:7:54). 

## Solution

Ensure the release convention is consistent across GitHub workflows.

**Comment by SHession** [comment]
It's possible we may be able to use the [extra plugins](https://github.com/cycjimmy/semantic-release-action#extra_plugins) part of the release action, similar to the this [issue](https://github.com/cycjimmy/semantic-release-action/issues/79#issuecomment-996458491).

**Comment by jonathonherbert** [comment]
This should be addressed by #223.
